- name: List existing vcsh configs
  shell: "{{ vendor_bin }}/vcsh list" 
  register: vcsh_list

# If it doesn't exist clone
- name: Clone editor config using vcsh
  command: "{{ vendor_bin }}/vcsh clone -b helix {{ git_repo }} helix"
  when: not vcsh_list.stdout is search("helix")

# If it already exists pull
- name: Pull editor config using vcsh
  command: "{{ vendor_bin }}/vcsh helix pull"
  when: vcsh_list.stdout is search("helix")

