- name: List existing vcsh configs
  shell: "{{ vendor_bin }}/vcsh list" 
  register: vcsh_list

# If it doesn't exist clone
- name: Clone editor config using vcsh
  command: /usr/bin/vcsh clone -b helix git@github.com:chopfitzroy/dotfiles-experiment.git helix
  when: not vcsh_list.stdout is search("helix")

# If it already exists pull
- name: Pull editor config using vcsh
  command: /usr/bin/vcsh helix pull
  when: vcsh_list.stdout is search("helix")

