- import_tasks: opensuse.yml
  when: ansible_os_family == "Suse"
- import_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- name: Set users default shell to Zsh
  become: yes
  user: 
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
      
